name: "DAST â€“ Fastbank Auth Lab"

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install app dependencies
      - name: Install dependencies
        working-directory: fastbank-auth-lab
        run: npm install

      # Start the Fastbank Auth Lab server
      - name: Start application
        working-directory: fastbank-auth-lab
        run: |
          nohup npm start &
          sleep 10

      # OWASP ZAP Full Scan
      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: "http://localhost:3000"
          cmd-options: "-a"
          allow_issue_writing: true
          fail_on_warning: false
          fail_on_error: true

      # Upload ZAP Report (HTML)
      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-html-report
          path: report_html.html

      # Upload ZAP Markdown Report
      - name: Upload ZAP Markdown Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-md-report
          path: report_md.md

